services:
  php:
    container_name: php-tri-con
    build:
      context: .
      dockerfile: Dockerfile
    image: seekode-php-apache
    volumes:
      - ./src:/var/www/html/
    environment:
      XDEBUG_MODE: debug,developer
      XDEBUG_CONFIG: remote_enable=1 remote_autostart=1
    ports:
      - 80:80
    networks:
      - app-network

  mariadb:
    container_name: mariadb-tri-con
    image: mariadb
    volumes:
      - ./database:/var/lib/mariadb:Z
    environment:
      MARIADB_ROOT_PASSWORD: pw
      MARIADB_DATABASE: database
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    networks:
      - app-network

  phpmyadmin:
    container_name: phpmyadmin-tri-con
    image: phpmyadmin
    depends_on:
      - mariadb
    environment:
      PMA_ROOT_USER: root
      PMA_ROOT_PASSWORD: root
      PMA_HOST: mariadb-tri-con
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
